// medicines

let medicines = {
    Acetaminophen:
    {
        genericName: " acetaminophen (oral) (a SEET a MIN oh fen)",
        brandName: [
            "Actamin", "Anacin AF", "Apra", " Bromo Seltzer", "Children's Tylenol", " Elixsure Fever/Pain", "Mapap", "Medi-Tabs", "Q-Pap",
        ],
        use: "",
        price: "200",
        dosage: "normal ",
        ingredients: [
            "Butalbital", "Endocet", "Tylox", "Ultracet", "Vicodin", "and Zydone"
        ],
        type: "pain reliver",
        isAvailable: "everywhere",
        forChildren: "half",
        forAdult: "1",
        properties: ["fiver reduce"],
        disadvantage: ["none"],
        rating: "5",
        inColor: "white",
        inBox: "true",
        isStore: "true",
        forTemprature: "20-26",
    },

    Adderall:
    {
        genericName: " amphetamine and dextroamphetamine (am FET a meen and DEX troe am FET a meen",
        brandNames: " Adderall, Adderall XR, Mydayi",
        use: "normal ",
        price: "300",
        dosage: "naormal",
        ingredients: "too many camical",
        type: "solid",
        isAvailable: "everywhere",
        forChildren: "noramla ",
        forAdult: "1",
        properties: [""],
        disadvantage: [""],
        rating: "5",
        inColor: "brown",
        inBox: "true",
        isStore: "yes",
        forTemprature: "20-24",
    },

    Alprazolam:
    {
        genericName: "alprazolam (al PRAY zoe lam)",
        brandNames: "Niravam, Xanax, Xanax XR",
        use: "internal",
        price: "400",
        dosage: "normal",
        ingredients: "tomuch chamical",
        type: "solid",
        isAvailable: "everywhre",
        forChildren: "normal",
        forAdult: "normal",
        properties: [""],
        disadvantage: [""],
        rating: "5",
        inColor: "white",
        inBox: "true",
        isStore: "yes",
        forTemprature: "24",
    },

    Amitriptyline:
    {
        genericName: "amitriptyline(a mee TRIP ti leen)",
        brandNames: " Vanatrip, Elavil, Endep",
        use: "external",
        price: "700",
        dosage: "useable",
        ingredients: "",
        type: "solid",
        isAvailable: "everywhere",
        forChildren: "normal",
        forAdult: "normal",
        properties: [""],
        disadvantage: ["none"],
        rating: "5",
        inColor: "red",
        inBox: "true",
        isStore: "true",
        forTemprature: "26",
    },

    Amlodipine:
    {
        genericName: "amlodipine (am LOE di peen)",
        brandNames: "Norvasc",
        use: "internal",
        price: "600",
        dosage: "normal",
        ingredients: "",
        type: "solid",
        isAvailable: "everywhere",
        forChildren: "0.5",
        forAdult: "1",
        properties: [""],
        disadvantage: [""],
        rating: "5",
        inColor: "white",
        inBox: "true",
        isStore: "true",
        forTemprature: "26",
    },

    Amoxicillin:
    {
        genericName: "amoxicillin (am OX i sil in)",
        brandNames: "Amoxil, Moxatag",
        use: "internal",
        price: "9786",
        dosage: "normal",
        ingredients: "",
        type: "liquid",
        isAvailable: "everywhere",
        forChildren: "normal",
        forAdult: "1",
        properties: [""],
        disadvantage: [""],
        rating: "5",
        inColor: "white",
        inBox: "true",
        isStore: "true",
        forTemprature: "24",
    },

    Ativan:
    {
        genericName: "lorazepam (oral) (lor A ze pam)",
        brandNames: "Ativan",
        use: "internal",
        price: "653",
        dosage: "normal",
        ingredients: "",
        type: "solid",
        isAvailable: "everywhere",
        forChildren: "normal",
        forAdult: "1",
        properties: [""],
        disadvantage: [""],
        rating: "5",
        inColor: "brown",
        inBox: "true",
        isStore: "true",
        forTemprature: "26",
    },

    Atorvastatin:
    {
        genericName: "atorvastatin (a TOR va sta tin)",
        brandNames: "Lipitor",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Azithromycin:
    {
        genericName: "ciprofloxacin (oral) (SIP roe FLOX a sin)",
        brandNames: "Cipro, Cipro XR, Proquin XR",
        genericName: "azithromycin (a ZITH roe MYE sin)",
        brandNames: " Azasite, Azithromycin 3 Day Dose Pack, Azithromycin 5 Day Dose Pack, Zithromax, Zithromax TRI-PAK, Zithromax Z-Pak, Zmax",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Ciprofloxacin:
    {
        genericName: " citalopram (si TAL o pram)",
        brandNames: "CeleXA",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Citalopram:
    {
        genericName: "clonazepam (kloe NAZ e pam)",
        brandNames: "KlonoPIN",
        genericName: "clindamycin (oral/injection) (klin da MYE sin)",
        brandNames: " Cleocin HCl, Cleocin Pediatric, Cleocin Phosphate, Cleocin Phosphate ADD-Vantage, Clindesse, ClindaMax Vaginal",
        use: "normal",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Clindamycin:
    {
        genericName: "clindamycin (oral/injection) (klin da MYE sin)",
        brandNames: "Cleocin HCl, Cleocin Pediatric, Cleocin Phosphate, Cleocin Phosphate ADD-Vantage, Clindesse, ClindaMax Vaginal",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Clonazepam:
    {
        genericName: "codeine(KOE deen)",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },

    Codeine: {
        genericName: "clonazepam (kloe NAZ e pam)",
        brandNames: "KlonoPIN",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Cyclobenzaprine: {
        genericName: "cyclobenzaprine (sye kloe BEN za preen)",
        brandNames: " Amrix, Comfort Pac with Cyclobenzaprine, Fexmid, Flexeril",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Cymbalta: {
        genericName: " duloxetine (du LOX e teen)",
        brandNames: " Cymbalta, Irenka",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Doxycycline: {
        genericName: " doxycycline (DOX i SYE kleen)",
        brandNames: "Acticlate, Adoxa CK, Adoxa Pak, Adoxa TT, Alodox, Avidoxy, Doryx, ",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",

    },
    Gabapentin: {
        genericName: "gabapentin (GA ba PEN tin)",
        grandNames: "Gralise, Horizant, Neurontin",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Hydrochlorothiazide: {
        genericName: "hydrochlorothiazide (HYE dro KLOR o THY a zide)",
        brandNames: "Microzide",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Ibuprofen: {
        genericName: "ibuprofen (EYE bue PROE fen)",
        brandNames: "Advil, Midol, Motrin, Motrin IB, Motrin Migraine Pain",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Lexapro: {
        genericName: "escitalopram (EE sye TAL o pram)",
        brandNames: "Lexapro",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Lisinopril: {
        genericName: "lisinopril (lyse IN oh pril)",
        brandNames: "Prinivil, Qbrelis, Zestril",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Loratadine: {
        genericName: "loratadine (lor AT a deen)",
        brandNames: "Alavert, Claritin, Claritin Reditab, Clear-Atadine",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Lorazepam: {
        genericName: "lorazepam (oral) (lor A ze pam)",
        brandNames: "Ativan, LORazepam Intensol",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Losartan: {
        genericName: " lorazepam (oral) (lor A ze pam)",
        brandNames: "Ativan, LORazepam Intensol",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Lyrica: {
        genericName: "pregabalin (pre GAB a lin)",
        brandNames: " Lyrica, Lyrica CR",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Meloxicam: {
        genericName: " meloxicam (mel OKS i kam)",
        brandNames: "Mobic, Vivlodex, Meloxicam Comfort Pac [DSC]",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Metformin: {
        genericName: "metformin (met FOR min)",
        brandNames: "Fortamet, Glucophage, Glucophage XR, Glumetza. Riomet",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Metoprolol: {
        genericName: "metoprolol (me TOE pro lol)",
        brandNames: " Kapspargo Sprinkle, Lopressor, Toprol-XL",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Naproxen: {
        genericName: " naproxen (na PROX en)",
        brandNames: " Aleve, EC-Naprosyn, Flanax Pain Reliever, Midol Extended Relief,",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Omeprazole: {
        genericName: " omeprazole (oh MEP ra zol)",
        brandNames: "FIRST Omeprazole, Omeprazole + SyrSpend SF Alka, PriLOSEC, ",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Oxycodone: {
        genericName: " oxycodone (ox i KOE done)",
        brandNames: "Oxaydo, OxyCONTIN, Oxyfast, Roxicodone, Xtampza ER",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Pantoprazole: {
        genericName: "pantoprazole (oral/injection) (pan TOE pra zole)",
        brandNames: "Protonix",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",

    },
    Prednisone: {
        genericName: "prednisone (PRED ni sone)",
        brandNames: " Rayos, Sterapred, Deltasone",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Tramadol: {
        genericName: "tramadol (TRAM a dol)",
        brandNames: "ConZip, Ultram, Ultram ER",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Trazodone: {
        genericName: "trazodone (TRAZ oh done)",
        brandNames: "Desyrel, Desyrel Dividose, Oleptro",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Viagra: {
        genericName: "sildenafil (oral) (sil DEN a fil)",
        brandNames: "Revatio, Viagra",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Wellbutrin: {
        genericName: "bupropion (byoo PRO pee on)",
        brandNames: " Aplenzin, Buproban, Forfivo XL, Wellbutrin SR, Wellbutrin XL, Zyban, ",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Xanax: {
        genericName: "alprazolam (al PRAY zoe lam)",
        brandNames: " Niravam, Xanax, Xanax XR",
        use: "",
        price: "",
        dosage: "",
        ingredients: "",
        type: "",
        isAvailable: "",
        forChildren: "",
        forAdult: "",
        properties: [""],
        disadvantage: [""],
        rating: "",
        inColor: "",
        inBox: "",
        isStore: "",
        forTemprature: "",
    },
    Zoloft: {
        genericName: "sertraline (SER tra leen)",
        brandNames: "Zoloft",
        use: "external",
        price: "200",
        dosage: "1",
        ingredients: ["bundle of chamical"],
        type: "solid",
        isAvailable: "everywhere",
        forChildren: "half",
        forAdult: "1",
        properties: ["pain realif"],
        disadvantage: ["no"],
        rating: "5",
        inColor: "white",
        inBox: "tru",
        isStore: "tru",
        forTemprature: "20-26",
    },
    drugSideEffects: [
        "Adderall",
        "Ambien",
        "Crestor",
        "Cymbalta",
        "Flomax",
        "Lexapro",
        "Lipitor",
        "lisinopril",
        "melatonin",
        "etformin",
        "Paxil",
        "Prozac",
        "simvastatin",
        " Tamiflu",
        "Viagra",
        "Vicodin",
        "Wellbutrin",
        "Xanax",
        "Zoloft",
    ],
    CommonDiseasesAndconditions: [
        "Erectile Dysfunction (Male)",
        "Female Pattern Baldness",
        " Fibromyalgia",
        "Gastroesophageal Reflux Disease (GERD)",
        " Gastrointestinal Disorders",
        "Hair Loss",
        " Hay Fever",
        "Heart Disease",
        "Hemorrhoids",
        " High Cholesterol",
        "Irritable Bowel Syndrome (IBS)",
        "Lung Cancer",
        " Male Pattern Baldness",
        "Menopause",
        "Mental Health",
        "Osteoarthritis",
        " Overactive Bladder (OAB)",
        "Pain",
        " Peptic Ulcers",
        "Prostate Cancer",
        "Rheumatoid Arthritis",
        "Schizophrenia",
        "Sexual Dysfunction (Female)",
        "Sexual Health",
        " Skin Cancer and Melanoma",
        "Tinea Capitis (Head)",
        " Weight Gain",
        "Weight Loss",
        "HD(Adult)",
        "AIDS / HIV",
        "Allergies",
        "Anxiety & Panic Attacks",
        "Arthritis",
        "Asthma",
        "Bipolar Disorder",
        "Breast Cancer",
        "Cancer",
        "Cervical Cancer",
        "Contact Dermatitis",
        "Crohn's Disease",
        "Depression",
        "Diabetes",
        "Eczema"
    ],
    medFactsNaturalProductsAtoZIndex:[
        Ackee
        Aconite
        African Basil
        African Mango
        African Mint
        Agrimony
        AHCC
        Aletris
        Alfalfa
        Alkanna Root
        Allspice
        Almond/Almond Oil
        Aloe
        Alpha-Lipoic Acid
        Amazonian Basil
        Ambrette
        Andrachne
        Andrographis
        Angelica
        Anise
        Apple Cider Vinegar
        Apples
        Apricot
        Argania
        Arnica
        Artichoke
        Asafetida
        Ashwagandha
        Asparagus
        Astragalus
        Autumn Crocus
        Avocado
        L-arginine
L-carnitine
L-Theanine
Labrador Tea
Lady's Mantle
Laminaria
Larch
Lathyrus
Lavender
Lecithin
Leeches
Lemon
Lemon Balm
Lemon Myrtle
Lemon Verbena
Lemongrass
Lentinan
Lettuce Opium
Levant Berry
Licorice
Life Root
Linden
Lion's Mane Mushroom
Lithium Orotate
Bacillus Clausii
Baical Skullcap
Banaba
Barberry
Barley
Barley Grass
Bayberry
Bee Venom
Beetroot
Bergamot Juice
Bergamot Oil
Beta Glucans
Beta-Sitosterol
Betel Nut
Bethroot
Betony
Bilberry
Biotin
Bishop's Weed
Bitter Melon
Bitter Orange
Bittersweet Nightshade
Black Cohosh
Black Currant
Black Haw
Black Walnut
Blessed Thistle
Bloodroot
Blue Cohosh
Boldo
Boneset
Borage
Boron
Bovine Colostrum
Brahmi
Brewer's Yeast
Broccoli
Broom
Buchu
Bugleweed
Bupleurum
    ],
    topdoctors: {
        name:
            [
                "sadia",
                "mhdi",
                "batool",
                "ibrahim",
                "furqan",
                "qadir",
                "rana faizan",
                "fazlur rehman",
                "adeel abrar",
                "kabil",
                "jawad",
                "buraq",
                "irbani",
                ""
            ],
        age:
            [
                23,
                24,
                35,
                56,
                45,
                67,
                23],
        addres: ["karachi"],
        cnic:
            [
                32423,
                3454,
                324324,
                435345,
                7656756,
                45435,
            ],
        profession: "tharopy",
        isInHospital: "karachi",
        time: "12-12pm",
        specialistOf: "skin",
        contact:
            [
                65545,
                -08098098,
                87665,
                54343,
                675657
            ],
        email: "top10doc@gmail.com"

    },
}
